<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Suppliers Export - {{ date('Y-m-d') }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #4472C4; }
        .header h1 { font-size: 20px; color: #4472C4; margin-bottom: 5px; }
        .header p { font-size: 11px; color: #666; }
        .info { margin-bottom: 15px; padding: 10px; background-color: #f5f5f5; border-radius: 4px; }
        .info p { margin: 3px 0; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        thead { background-color: #4472C4; color: white; }
        th { padding: 8px 5px; text-align: left; font-size: 8px; font-weight: bold; border: 1px solid #4472C4; }
        td { padding: 6px 5px; border: 1px solid #ddd; font-size: 8px; }
        tbody tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; text-align: center; font-size: 8px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Suppliers Export</h1>
        <p>Apex Electronics & Accessories</p>
        <p>Generated on: {{ $export_date }}</p>
    </div>
    <div class="info">
        <p><strong>Total Suppliers:</strong> {{ $total }}</p>
    </div>
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 15%;">Name</th>
                <th style="width: 15%;">Company</th>
                <th style="width: 12%;">Phone</th>
                <th style="width: 18%;">Email</th>
                <th style="width: 25%;">Address</th>
                <th style="width: 10%;">Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($suppliers as $index => $supplier)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $supplier->name }}</td>
                <td>{{ $supplier->company ?? '—' }}</td>
                <td>{{ $supplier->phone ?? '—' }}</td>
                <td>{{ $supplier->email ?? '—' }}</td>
                <td>{{ \Illuminate\Support\Str::limit($supplier->address ?? '—', 40) }}</td>
                <td>{{ $supplier->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="padding: 20px; text-align: center;">No suppliers found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">
        <p>Generated by Apex Electronics & Accessories Management System — {{ $export_date }}</p>
    </div>
</body>
</html>
