<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchases Export - {{ date('Y-m-d') }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 10px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #4472C4; }
        .header h1 { font-size: 20px; color: #4472C4; margin-bottom: 5px; }
        .header p { font-size: 11px; color: #666; }
        .info { margin-bottom: 15px; padding: 10px; background-color: #f5f5f5; border-radius: 4px; }
        .info p { margin: 3px 0; font-size: 9px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        thead { background-color: #4472C4; color: white; }
        th { padding: 8px 5px; text-align: left; font-size: 8px; font-weight: bold; border: 1px solid #4472C4; }
        td { padding: 6px 5px; border: 1px solid #ddd; font-size: 8px; }
        .text-right { text-align: right; }
        tbody tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #ddd; text-align: center; font-size: 8px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Purchases Export</h1>
        <p>Apex Electronics & Accessories</p>
        <p>Generated on: {{ $export_date }}</p>
    </div>
    <div class="info">
        <p><strong>Total Purchases:</strong> {{ $total }} &nbsp;|&nbsp; <strong>Total Amount:</strong> {{ number_format($total_amount, 2) }} UGX</p>
    </div>
    <table>
        <thead>
            <tr>
                <th style="width: 5%;">#</th>
                <th style="width: 18%;">Invoice #</th>
                <th style="width: 22%;">Supplier</th>
                <th style="width: 12%;">Date</th>
                <th style="width: 18%;" class="text-right">Total (UGX)</th>
                <th style="width: 15%;">Created By</th>
                <th style="width: 10%;">Created At</th>
            </tr>
        </thead>
        <tbody>
            @forelse($purchases as $index => $purchase)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $purchase->invoice_number }}</td>
                <td>{{ $purchase->supplier?->name ?? '—' }}</td>
                <td>{{ $purchase->purchase_date->format('Y-m-d') }}</td>
                <td class="text-right">{{ $purchase->total_amount ? number_format($purchase->total_amount, 2) : '—' }}</td>
                <td>{{ $purchase->creator?->name ?? '—' }}</td>
                <td>{{ $purchase->created_at->format('Y-m-d H:i') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="padding: 20px; text-align: center;">No purchases found</td>
            </tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">
        <p>Generated by Apex Electronics & Accessories Management System — {{ $export_date }}</p>
    </div>
</body>
</html>
